# Configuration for connection pg_orders_clickhouse
definition_type: connection
resource_name: "pg_orders_clickhouse"
source_configuration_path: sources/pg_orders/configuration.yaml
destination_configuration_path: destinations/clickhouse/configuration.yaml

# EDIT THE CONFIGURATION BELOW!
configuration:
  status: active # REQUIRED | string | Allowed values: active, inactive, deprecated
  skip_reset: false # OPTIONAL | boolean | Flag to check if the connection should be reset after a connection update
  namespace_definition: destination # OPTIONAL | string | Allowed values: source, destination, customformat
  namespace_format: "" # OPTIONAL | string | Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If "${SOURCE_NAMESPACE}" then behaves like namespaceDefinition = 'source'.
  prefix: "" # REQUIRED | Prefix that will be prepended to the name of each stream when it is written to the destination
  resource_requirements: # OPTIONAL | object | Resource requirements to run workers (blank for unbounded allocations)
    cpu_limit: "" # OPTIONAL
    cpu_request: "" # OPTIONAL
    memory_limit: "" # OPTIONAL
    memory_request: "" # OPTIONAL
  schedule_type: manual # OPTIONAL | string | Allowed values: basic, cron, manual
  # schedule_data: # OPTIONAL | object
  #   basic_schedule:
  #     time_unit: hours # REQUIRED | string | Allowed values: minutes, hours, days, weeks, months
  #     units: 1 # REQUIRED | integer
  #   cron:
  #     cron_time_zone: "UTC" # REQUIRED | string
  #     cron_expression: "* */2 * * * ?" # REQUIRED | string
  operations:
    ## -------- Uncomment and edit the block below if you want to enable Airbyte normalization --------
    - name: "Normalization"
      operator_configuration:
        normalization:
          option: "basic"
        operator_type: "normalization"
  sync_catalog: # OPTIONAL | object | 🚨 ONLY edit streams.config, streams.stream should not be edited as schema cannot be changed.
    streams:
      - config:
          alias_name: payments
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key:
            - - id
          selected: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            properties:
              amount:
                airbyte_type: integer
                type: number
              id:
                airbyte_type: integer
                type: number
              order_id:
                airbyte_type: integer
                type: number
              payment_method:
                type: string
            type: object
          name: payments
          namespace: public
          source_defined_primary_key:
            - - id
          supported_sync_modes:
            - full_refresh
            - incremental
      - config:
          alias_name: orders
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key:
            - - id
          selected: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            properties:
              id:
                airbyte_type: integer
                type: number
              order_date:
                format: date
                type: string
              status:
                type: string
              user_id:
                airbyte_type: integer
                type: number
            type: object
          name: orders
          namespace: public
          source_defined_primary_key:
            - - id
          supported_sync_modes:
            - full_refresh
            - incremental
