default:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: processed_customers
      host: clickhouse
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
