version: 2
models:
  - name: customers
    description: Model for customers.
    columns:
      - name: customer_id
        description: Primary key.
        tests:
          - not_null
          - unique
      - name: first_name
        description: Customer's first name.
        tests:
          - not_null
      - name: last_name
        description: Customer's last name.
        tests:
          - not_null
      - name: phone_number
        description: Customer's phone number.

  - name: orders
    description: Model for orders.
    columns:
      - name: order_id
        description: Primary key.
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Foreign key to customers model.
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: order_date
        description: Date of the order.
        tests:
          - not_null
      - name: order_status
        description: Status of the order.
        tests:
          - not_null
          - accepted_values:
              values:
                - completed
                - placed
                - return_pending
                - returned
                - shipped
      - name: order_amount
        description: The total amount of the order.
        tests:
          - not_null
